# Generated by Django 2.2.4 on 2019-09-03 15:29

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('vorname', models.CharField(max_length=144, verbose_name='Vorname')),
                ('nachname', models.CharField(max_length=144, verbose_name='Nachname')),
                ('code', models.CharField(max_length=8, verbose_name='Zugangscode')),
                ('seminarort', models.CharField(choices=[('Kiel', 'Kiel, 19.-22.9.19'), ('Dresden', 'Dresden, 3.-6.10.19')], max_length=144, verbose_name='Seminarort')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
                'ordering': ('-modified', '-created'),
            },
        ),
    ]
