# Generated by Django 2.2.4 on 2019-09-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Themenwahl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Aufgabenseminar Edynamik',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='Experiment: Brechungsindex von Wasser',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='Experiment: Erdmagnetfeld',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='Experimentieren und Auswerten',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='Klassische Mechanik',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='Quantenmechanik II',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='Spezielle Funktionen und Vektorrechnung',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
