# Generated by Django 2.2.4 on 2019-09-03 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Themenwahl', '0002_auto_20190903_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Aufgabenseminar Edynamik',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Experiment: Brechungsindex von Wasser',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Experiment: Erdmagnetfeld',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Experimentieren und Auswerten',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Klassische Mechanik',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Quantenmechanik II',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Spezielle Funktionen und Vektorrechnung',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
    ]
