# Generated by Django 2.2.4 on 2019-09-04 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Themenwahl', '0005_auto_20190904_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Aufgabenseminar Edynamik',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Aufgabenseminar Elektrodynamik',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Aufgabenseminar Quanten- und Atomphysik und Struktur der Materie',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Aufgabenseminar SRT',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Aufgabenseminar Wärmelehre',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Aufgabenseminar klassische Mechanik',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Bestimmung des Brechungskoeffizienten von Plexiglas',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Bestimmung des Brechungskoeffizienten von Wasser',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Einführung ins Differenzieren',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Einführung ins Integrieren',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Elektrische Blackboxen',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Elektrische Schaltungen',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Elektrodynamik 1',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Elektrodynamik 2',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Elektronik',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Energie im Kondensator',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Experiment: Brechungsindex von Wasser',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Experiment: Erdmagnetfeld',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Experimentieren und Auswerten',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Fallender Doppler-Effekt',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Fluiddynamik',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Geometrische Optik',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Gewöhnliche Differentialgleichungen',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Gravitationsbeschleunigung',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Halleffekt',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Harmonische Schwingungen',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Himmelsmechanik',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Hören',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Ideales Gas',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Kernphysik',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Klassische Mechanik',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Komplexe Wechselstromrechnung',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Leuchtdioden und Plancksches Winkumsquantum',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Näherungsmethoden',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Pohlsches Rad',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Quanten- und Atomphysik I',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Quanten- und Atomphysik II',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Relativistische Teilchenphysik',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Reversionspendel',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Rotationsbewegungen',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Schallgeschwindigkeit in Metallen',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Spezielle Funktionen und Vektorrechnung',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Spezielle Relativitätstheorie',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Theoretische Mechanik',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Thermodynamik 1',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Thermodynamik 2 - Statistische Physik',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Thermographie an einem Modellhaus',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Torsionsschwingung',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Videoanalyse von Stößen ausgedehnter Körper auf einem Luftkissentisch',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Wechselstrombrücke',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Wellenoptik',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='Zylindrische Körper im Wasser',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
    ]
