# Generated by Django 2.2.4 on 2019-09-05 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Themenwahl', '0007_person_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Elektronik',
        ),
        migrations.RemoveField(
            model_name='person',
            name='Harmonische Schwingungen',
        ),
        migrations.RemoveField(
            model_name='person',
            name='Quanten- und Atomphysik II',
        ),
    ]
