# Generated by Django 2.2.4 on 2019-09-10 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Themenwahl', '0009_auto_20190905_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Thermodynamik 2 - Statistische Physik',
        ),
    ]
