# Generated by Django 2.2.4 on 2019-09-12 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Themenwahl', '0010_remove_person_thermodynamik 2 - statistische physik'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Elektrische Schaltungen',
            new_name='Grundlagen der Elektrik',
        ),
        migrations.AddField(
            model_name='person',
            name='Marieneehrenmal',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AddField(
            model_name='person',
            name='Mediendom/Computermuseum',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
        migrations.AddField(
            model_name='person',
            name='Stadtführung',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Bitte Wert 0-4 eingeben'), django.core.validators.MaxValueValidator(4, message='Bitte Wert 0-4 eingeben')]),
        ),
    ]
