# Generated by Django 2.2.3 on 2019-07-29 08:47

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teilnahme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('vorname', models.CharField(max_length=144)),
                ('nachname', models.CharField(max_length=144)),
                ('geschlecht', models.CharField(choices=[('m', 'm'), ('w', 'w')], max_length=1)),
                ('email', models.EmailField(max_length=144, unique=True)),
                ('geburtsdatum', models.DateField()),
                ('telefon', models.CharField(blank=True, max_length=144, verbose_name='Telefonnummer zur Planung der Anreise')),
                ('notfallnummer', models.CharField(max_length=144, verbose_name='Telefonnummer der Eltern für Notfälle')),
                ('essenswünsche', models.TextField(blank=True, verbose_name='Besondere Essenswünsche (vegan, koscher, etc)')),
                ('beeinträchtigungen', models.TextField(blank=True, verbose_name='Körperliche Beeinträchtigugen (z.B. Rollstuhl)')),
                ('weitere_hinweise', models.TextField(blank=True, verbose_name='Weitere Hinweise')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
