# Generated by Django 2.2.4 on 2019-08-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teilnahme',
            name='bundesland',
            field=models.CharField(default=' ', max_length=144, verbose_name='Bundesland'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teilnahme',
            name='schule',
            field=models.CharField(default=' ', max_length=144, verbose_name='Schule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teilnahme',
            name='email',
            field=models.EmailField(max_length=144, unique=True, verbose_name='eMail'),
        ),
        migrations.AlterField(
            model_name='teilnahme',
            name='geschlecht',
            field=models.CharField(choices=[('m', 'm'), ('w', 'w')], max_length=1, verbose_name='Geschlecht'),
        ),
        migrations.AlterField(
            model_name='teilnahme',
            name='nachname',
            field=models.CharField(max_length=144, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='teilnahme',
            name='vorname',
            field=models.CharField(max_length=144, verbose_name='Vorname'),
        ),
    ]
