# Generated by Django 2.2.4 on 2019-08-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0002_auto_20190816_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='teilnahme',
            name='teilnehmercode',
            field=models.CharField(blank=True, max_length=144, verbose_name='Teilnehmercode für die PhysikOlympiade (falls vorhanden)'),
        ),
    ]
