# Generated by Django 2.2.4 on 2019-08-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0003_teilnahme_teilnehmercode'),
    ]

    operations = [
        migrations.AddField(
            model_name='teilnahme',
            name='seminarort',
            field=models.CharField(choices=[('Kiel, 19.-22.9.19', 'Kiel'), ('Dresden, 3.-6.10.19', 'Dresden')], default='Kiel', max_length=144, verbose_name='Seminarort'),
            preserve_default=False,
        ),
    ]
