# Generated by Django 2.2.4 on 2019-08-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0004_teilnahme_seminarort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teilnahme',
            name='seminarort',
            field=models.CharField(choices=[('Kiel', 'Kiel, 19.-22.9.19'), ('Dresden', 'Dresden, 3.-6.10.19')], max_length=144, verbose_name='Seminarort'),
        ),
    ]
