# Generated by Django 2.2.4 on 2019-08-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0005_auto_20190820_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='teilnahme',
            name='formulardatei',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
