# Generated by Django 2.2.4 on 2019-08-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0006_teilnahme_formulardatei'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teilnahme',
            options={'verbose_name_plural': 'Anmeldungen'},
        ),
        migrations.AddField(
            model_name='teilnahme',
            name='runtergeladen',
            field=models.BooleanField(default=False),
        ),
    ]
