# Generated by Django 2.2.4 on 2019-08-20 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0007_auto_20190820_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='teilnahme',
            name='datum_eingegangen',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
